import './declarations'
import './global-styles.ts';
import './controls/chat-text-area';
import './controls/chat-container';
import './controls/chat-toggle';
import './controls/chat-button';
import './controls/chat-slider';
import './controls/chat-app';
import './controls/chat-icon';
import './controls/chat-radio';
import './app-data';
